# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-09 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.SlugField(max_length=64, primary_key=True, serialize=False, verbose_name='Label')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation date/time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last update date/time')),
                ('title', models.CharField(max_length=128, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
