# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-26 18:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognition', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='label',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='label',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Ordering'),
            preserve_default=False,
        ),
    ]
