# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-31 18:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('recognition', '0002_auto_20161026_1854'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabelCombination',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False, verbose_name='Unique identifier')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation date/time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last update date/time')),
                ('description_template', models.TextField(help_text='What these two labels would be described together? Use {primary_side} and {secondary_side} placeholders!', verbose_name='Description template')),
                ('primary_label', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='recognition.Label', verbose_name='Primary label')),
                ('secondary_label', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='recognition.Label', verbose_name='Secondary label')),
            ],
            options={
                'ordering': ['-primary_label__order', '-secondary_label__order'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='labelcombination',
            unique_together=set([('primary_label', 'secondary_label')]),
        ),
    ]
