# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-03 13:16
from __future__ import unicode_literals

from django.db import migrations, models
import uuid
import webcam.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False, verbose_name='Unique identifier')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creation date/time')),
                ('image', models.ImageField(height_field='height', upload_to=webcam.models.get_picture_path, verbose_name='Camera snapshot image', width_field='width')),
                ('width', models.PositiveIntegerField(verbose_name='Image width')),
                ('height', models.PositiveIntegerField(verbose_name='Image height')),
            ],
        ),
    ]
