# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-09 18:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recognition', '0001_initial'),
        ('webcam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='label',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pictures', to='recognition.Label', verbose_name='Label'),
        ),
    ]
