# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-28 19:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recognition', '0002_auto_20161026_1854'),
        ('webcam', '0003_auto_20161129_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='recognized_left_label',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='recognized_left_pictures', to='recognition.Label', verbose_name='Recognized left-side label'),
        ),
        migrations.AddField(
            model_name='picture',
            name='recognized_right_label',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='recognized_right_pictures', to='recognition.Label', verbose_name='Recognized right-side label'),
        ),
    ]
