# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-29 19:58
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcam', '0004_auto_20161228_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='recognized_left_probability',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Recognized left-side label probability'),
        ),
        migrations.AddField(
            model_name='picture',
            name='recognized_right_probability',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Recognized right-side label probability'),
        ),
    ]
